name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}, DB ${{ matrix.db }}, SMW ${{ matrix.smw }}"
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - mw: 'REL1_43'
            php: '8.1'
            db: 'mysql'
            smw: 'dev-master'
            experimental: true
          - mw: 'REL1_43'
            php: '8.3'
            db: 'mysql'
            smw: 'dev-master'
            experimental: true
          - mw: 'REL1_43'
            php: '8.3'
            db: 'sqlite'
            smw: 'dev-master'
            experimental: true
          - mw: 'master'
            php: '8.4'
            db: 'mysql'
            smw: 'dev-master'
            experimental: true

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: 1
          MYSQL_DATABASE: mediawiki
          MYSQL_USER: mediawiki
          MYSQL_PASSWORD: mediawiki

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v4
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}-${{ matrix.db }}-smw${{ matrix.smw }}_v1

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v4
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true' || matrix.db == 'mysql'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} ${{ matrix.db }} ${{ matrix.smw }} ModernTimeline

      - uses: actions/checkout@v4
        with:
          path: mediawiki/extensions/ModernTimeline

      - run: composer update

      - name: Run update.php
        run: php maintenance/update.php --quick

      - name: Run PHPUnit
        run: php tests/phpunit/phpunit.php -c extensions/ModernTimeline/
        if: matrix.mw != 'master'

      - name: Run PHPUnit with code coverage
        run: php tests/phpunit/phpunit.php -c extensions/ModernTimeline/ --coverage-clover coverage.xml
        if: matrix.mw == 'master'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.mw == 'master'

  PHPStan:
    name: "PHPStan: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: '8.3'
            db: 'sqlite'
            smw: 'dev-master'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer, cs2pr

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v4
        with:
          path: |
            mediawiki
            mediawiki/extensions/
            mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}_v1

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer_static_analysis

      - uses: actions/checkout@v4
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} ${{ matrix.db }} ${{ matrix.smw }} ModernTimeline

      - uses: actions/checkout@v4
        with:
          path: mediawiki/extensions/ModernTimeline

      - name: Composer allow-plugins
        run: composer config --no-plugins allow-plugins.composer/installers true

      - run: composer update

      - name: Composer install
        run: cd extensions/ModernTimeline && composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPStan
        run: cd extensions/ModernTimeline && php vendor/bin/phpstan analyse --error-format=checkstyle --no-progress | cs2pr

  phpcs:
    name: "Code style: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: '8.3'
            db: 'sqlite'
            smw: 'dev-master'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki/extensions/ModernTimeline

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, php-ast
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v4
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_static_analysis

      - name: Cache Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer_static_analysis

      - uses: actions/checkout@v4
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} ${{ matrix.db }} ${{ matrix.smw }} ModernTimeline

      - uses: actions/checkout@v4
        with:
          path: mediawiki/extensions/ModernTimeline

      - name: Composer install
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - run: vendor/bin/phpcs -p -s
